FROM python:3.9

RUN pip install "poetry==1.4.1"
COPY LogResultAccumulator/src/log_builder_sender/ /logger/
COPY pyproject.toml /logger/
WORKDIR /logger/
RUN poetry install
WORKDIR /

CMD ["poetry", "run", "python", "-m", "logger.main"]